name: Kontrola Liptovska Osada

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:


jobs:
  kontrola:

    runs-on: ubuntu-latest

    permissions:
      contents: write


    steps:

    - name: Stiahnutie kodu
      uses: actions/checkout@v4


    - name: Nastavenie Pythonu
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"


    - name: Instalacia balikov
      run: |
        pip install -r requirements.txt


    - name: Spustenie kontroly
      run: |
        python monitor.py


    - name: Ulozenie noveho stavu
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add page_hash.txt
        git commit -m "Update page hash" || echo "No changes to commit"
        git push
